language: swift
cache: cocoapods
podfile: Podfile
osx_image: xcode9.3
before_install:
  - brew update
  - gem install cocoapods
  - gem install fir-cli
  - pod repo update
  - pod install
before_script:
#  - "./scripts/env.sh"
  - "./scripts/add-key.sh"
script:
  - "travis_wait 60 ./scripts/travis.sh"
after_success:
  - "./scripts/sign-and-upload.sh"
after_script:
  - "./scripts/remove-key.sh"
env:
  global:
  - APPNAME="Monkey"
notifications:
  webhooks:
  - https://oapi.dingtalk.com/robot/send?access_token=61f86afa97713269efd5381cb4f33d49228a7f0d249df2384e50ae2bb82e64a6

#  - SCHEME_RELEASE="Release"
#  - SCHEME_SANDBOX="Sandbox"
